services:
  db:
    image: postgres:15
    container_name: pg_container
    restart: always
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5565:5432"

volumes:
  pgdata:
